import Foundation

/// [教程注释：多语言简易实现]
/// 结构体 `L` (Localization) 提供了一个硬编码的多语言词典方案。
/// 对于小型独立 App 来说，这比配置官方的 Localizable.strings 更加直观和容易修改。
struct L {
    // [逻辑流程]
    // 静态方法 (static func)：不需要实例化 L 即可调用。例如 `L.s("Save", .zh)`。
    // 如果字典里找不到对应的语言翻译，则使用 `??` (Nil-Coalescing Operator) 降级返回原 Key。
    // [P0修复] 将字典提升为 static let，避免每次调用都重新创建 100+ 条目的字典
    private static let dict: [String: [AppLanguage: String]] = [
            "Link Preview Unavailable": [.zh: "暂时无法生成预览，可直接跳转到链接位置。", .en: "Preview unavailable. You can go directly to the link destination."],
            "Go to Link Destination": [.zh: "跳转到链接位置", .en: "Go to link destination"],
            "Unknown Link": [.zh: "无法识别链接", .en: "Unknown link"],
            "Refresh": [.zh: "刷新", .en: "Refresh"],
            "Tomorrow": [.zh: "明天", .en: "Tomorrow"],
            "Current Paper": [.zh: "本文献", .en: "Current Paper"],
            "App List": [.zh: "App专属", .en: "App List"],
            "Return to Today": [.zh: "回到今天", .en: "Return to Today"],
            "New Event Slot Hint": [.zh: "双击时间槽新建", .en: "Double-click a time slot to add an event"],
            "Add Event Here": [.zh: "双击在此时间添加日程", .en: "Double-click to add an event here"],
            "Task Example": [.zh: "例如：精读第三节哈密顿量推导", .en: "For example: review the Hamiltonian derivation in section 3"],
            "Event Example": [.zh: "例如：文献阅读与推导研讨", .en: "For example: paper reading and derivation discussion"],
            "Add to Reminders": [.zh: "添加至提醒事项", .en: "Add to Reminders"],
            "Add to Calendar": [.zh: "添加至日历", .en: "Add to Calendar"],
            "Untitled Task": [.zh: "未命名待办", .en: "Untitled Task"],
            "Untitled Event": [.zh: "未命名日程", .en: "Untitled Event"],
            "All-day Event": [.zh: "全天日程", .en: "All-day Event"],
            "Delete Task": [.zh: "删除待办", .en: "Delete Task"],
            "Mark Incomplete": [.zh: "标记为未完成", .en: "Mark Incomplete"],
            "Mark Complete": [.zh: "标记为已完成", .en: "Mark Complete"],
            "Permission Not Enabled": [.zh: "权限未开启或已被拒绝", .en: "Access is disabled or denied"],
            "Schedule Access Denied": [.zh: "macOS 已限制访问%@。请在“系统设置 → 隐私与安全性 → %@”中允许 SimPleview。", .en: "macOS has restricted access to %@. Allow SimPleview in System Settings → Privacy & Security → %@."],
            "Schedule Access Purpose": [.zh: "SimPleview 需要访问系统%@，以显示和更新待办或日程。", .en: "SimPleview needs access to %@ to display and update reminders or events."],
            "Paper Citation": [.zh: "来自文献: 《%@》 第 %ld 页", .en: "From paper: %@, page %ld"],
            "Reading Paper": [.zh: "研读: %@", .en: "Reading: %@"],
            "No Repeat": [.zh: "无", .en: "None"],
            "Repeat Daily": [.zh: "每天", .en: "Daily"],
            "Repeat Weekly": [.zh: "每周", .en: "Weekly"],
            "Repeat Biweekly": [.zh: "每两周", .en: "Every Two Weeks"],
            "Repeat Monthly": [.zh: "每月", .en: "Monthly"],
            "Repeat Yearly": [.zh: "每年", .en: "Yearly"],
            "No Alert": [.zh: "无", .en: "None"],
            "At Event Time": [.zh: "日程发生时", .en: "At Time of Event"],
            "5 Minutes Before": [.zh: "5 分钟前", .en: "5 Minutes Before"],
            "15 Minutes Before": [.zh: "15 分钟前", .en: "15 Minutes Before"],
            "30 Minutes Before": [.zh: "30 分钟前", .en: "30 Minutes Before"],
            "1 Hour Before": [.zh: "1 小时前", .en: "1 Hour Before"],
            "2 Hours Before": [.zh: "2 小时前", .en: "2 Hours Before"],
            "1 Day Before": [.zh: "1 天前", .en: "1 Day Before"],
            "2 Days Before": [.zh: "2 天前", .en: "2 Days Before"],
            "Thumbnails": [.zh: "缩略图", .en: "Thumbnails"],
            "Outline": [.zh: "目录", .en: "Outline"],
            "Annotations": [.zh: "标注", .en: "Annotations"],
            "Search": [.zh: "搜索", .en: "Search"],
            "Reminder Access Required": [.zh: "未获得提醒事项访问权限", .en: "Access to reminders is required."],
            "Calendar Access Required": [.zh: "未获得日历访问权限", .en: "Full calendar access is required."],
            "Title Required": [.zh: "标题不能为空", .en: "Enter a title."],
            "Invalid Event Dates": [.zh: "结束时间不能早于开始时间", .en: "The end time cannot be earlier than the start time."],
            "Operation Failed": [.zh: "操作未完成", .en: "Operation Failed"],
            "Pomodoro": [.zh: "番茄钟", .en: "Pomodoro"],
            "Reading Session": [.zh: "阅读", .en: "Reading"],
            "Remaining Time": [.zh: "剩余时间", .en: "Remaining Time"],
            "Focus Duration": [.zh: "专注时长", .en: "Duration"],
            "Focus Duration Range": [.zh: "请输入 1–180 分钟的整数", .en: "Enter a whole number from 1 to 180 minutes."],
            "Focus Ready": [.zh: "准备开始", .en: "Ready to start"],
            "Focus Running": [.zh: "专注中", .en: "Focusing"],
            "Focus Awaiting Return": [.zh: "时间已到，等待返回应用", .en: "Time is up. Waiting for your return."],
            "Focus Completed": [.zh: "本次专注已完成", .en: "Focus session completed"],
            "Focus Failed": [.zh: "离开已满 5 分钟，本次失败", .en: "Away for 5 minutes. Session failed."],
            "Focus Cancelled": [.zh: "本次已取消", .en: "Session cancelled"],
            "Start Pomodoro": [.zh: "开始专注", .en: "Start Focus"],
            "Cancel Pomodoro": [.zh: "取消本次", .en: "Cancel Session"],
            "Focus Rules": [.zh: "切出应用不足 5 分钟可继续，满 5 分钟则失败。完成后按实际起止时间添加日程。", .en: "Return within 5 minutes when switching apps. Longer absences fail the session. Completed sessions are added to your calendar with their start and end times."],
            "Automatic Reading Rule": [.zh: "未开番茄钟时，前台阅读满 1 小时会在本次阅读结束后自动添加日程。", .en: "Without a timer, foreground reading of at least 1 hour is added to your calendar when the reading session ends."],
            "Pending Calendar Records": [.zh: "待写入日历", .en: "Pending calendar entries"],
            "Authorize Calendar": [.zh: "授权日历", .en: "Authorize Calendar"],
            "Calendar Authorized": [.zh: "日历已授权", .en: "Calendar Authorized"],
            "Authorize Calendar in Settings": [.zh: "前往设置授权日历", .en: "Authorize Calendar in Settings"],
            "Calendar Authorization Shared": [.zh: "番茄钟与待办共用本应用的日历权限，无需重复授权。", .en: "Pomodoro and Todo share this app's calendar permission. No additional authorization is needed."],
            "Sync Calendar Records": [.zh: "补写记录", .en: "Sync Pending Records"],
            "Focus Calendar Permission": [.zh: "需要日历完整访问权限。已完成的记录会保留，授权后补写。", .en: "Full calendar access is required. Completed records are kept and can be synced after authorization."],
            "Focus Calendar Unavailable": [.zh: "没有可写入的日历，记录已保留。", .en: "No writable calendar is available. Your records are kept."],
            "Focus Save Before Quit": [.zh: "阅读日程尚未保存，已取消退出", .en: "Calendar records could not be saved. Quit cancelled."],
            "Todo": [.zh: "待办", .en: "Todo"],
            "Record": [.zh: "记录", .en: "Record"],
            "Reminders": [.zh: "提醒事项", .en: "Reminders"],
            "Schedule": [.zh: "日程安排", .en: "Schedule"],
            "Add Task": [.zh: "添加待办", .en: "Add Task"],
            "Add Event": [.zh: "添加日程", .en: "Add Event"],
            "Task Title": [.zh: "待办内容", .en: "Task Title"],
            "Event Title": [.zh: "日程标题", .en: "Event Title"],
            "Due Date": [.zh: "截止时间", .en: "Due Date"],
            "Start Time": [.zh: "开始时间", .en: "Start Time"],
            "End Time": [.zh: "结束时间", .en: "End Time"],
            "All Day": [.zh: "全天", .en: "All Day"],
            "Notes": [.zh: "备注说明", .en: "Notes"],
            "List": [.zh: "分类列表", .en: "List"],
            "Calendar": [.zh: "所属日历", .en: "Calendar"],
            "Filter Current Paper": [.zh: "仅看本文献", .en: "Current Paper Only"],
            "Attach Current Page": [.zh: "附带当前文献页码", .en: "Attach Current Page"],
            "Authorize Reminders & Calendar": [.zh: "授权访问系统提醒事项与日历", .en: "Authorize Reminders & Calendar"],
            "Permission Required": [.zh: "需要系统权限以直接联动 macOS 原生提醒与日历", .en: "Permissions required to sync with native macOS Reminders & Calendar"],
            "Open System Settings": [.zh: "打开系统设置", .en: "Open System Settings"],
            "Check Again": [.zh: "重新检测权限", .en: "Check Again"],
            "Permission Denied Guide": [.zh: "权限已被系统限制或拒绝，请前往系统设置开启", .en: "Permission restricted or denied. Please enable in System Settings"],
            "All Lists": [.zh: "全部列表", .en: "All Lists"],
            "SimPleview Reading": [.zh: "SimPleview阅读", .en: "SimPleview Reading"],
            "Completed": [.zh: "已完成", .en: "Completed"],
            "Today": [.zh: "今天", .en: "Today"],
            "Double-click to Add Event": [.zh: "双击添加日程", .en: "Double-click to Add Event"],
            "Edit Event": [.zh: "编辑日程", .en: "Edit Event"],
            "Event Name": [.zh: "日程名称", .en: "Event Name"],
            "Delete Event": [.zh: "删除日程", .en: "Delete Event"],
            "Repeat": [.zh: "重复", .en: "Repeat"],
            "Alert": [.zh: "提醒", .en: "Alert"],
            "Authorize Access": [.zh: "授权访问系统", .en: "Authorize Access to"],
            "No Reminders Found": [.zh: "暂无待办事项", .en: "No Reminders Found"],
            "No Events Found": [.zh: "近期无日程安排", .en: "No Events Found"],
            "Edit API": [.zh: "编辑 API", .en: "Edit API"],
            "New API (Unsaved)": [.zh: "新 API（未保存）", .en: "New API (Unsaved)"],
            "Add API": [.zh: "添加 API", .en: "Add API"],
            "Add from Template": [.zh: "从模板添加", .en: "Add from Template"],
            "Other Compatible API…": [.zh: "其他兼容接口…", .en: "Other Compatible API…"],
            "Connect Your AI": [.zh: "连接你的 AI", .en: "Connect Your AI"],
            "AI Connection Introduction": [.zh: "支持任意 OpenAI 兼容接口，可分别配置服务地址、密钥和模型。", .en: "Connect any OpenAI-compatible API, with a separate URL, API key, and model list for each connection."],
            "API Name": [.zh: "API 名称", .en: "API Name"],
            "API Name Placeholder": [.zh: "例如：工作接口、个人接口", .en: "For example: Work API or Personal API"],
            "Enter the API key for this connection": [.zh: "输入此接口的密钥", .en: "Enter the API key for this connection"],
            "AI Connection Help": [.zh: "填写服务商的基础地址，不含 /chat/completions。各 API 的密钥独立保存在钥匙串。", .en: "Enter the provider’s base URL without /chat/completions. Each API key is stored separately in Keychain."],
            "Connection Details": [.zh: "连接信息", .en: "Connection Details"],
            "Exact Model ID": [.zh: "精确模型 ID", .en: "Exact Model ID"],
            "Remove This Model": [.zh: "删除此模型", .en: "Remove This Model"],
            "Supports Images and PDF Reading": [.zh: "支持图片输入，可读取 PDF", .en: "Supports Images and PDF Reading"],
            "Adjust Budget": [.zh: "调整预算", .en: "Adjust Budget"],
            "Add Model": [.zh: "添加模型", .en: "Add Model"],
            "Exact Model ID Help": [.zh: "模型 ID 将原样发送给此 API。请按服务商提供的型号填写，并仅为支持图片的模型开启 PDF 阅读。", .en: "Model IDs are sent exactly as entered. Use the IDs supplied by your provider, and enable PDF reading only for models that support image input."],
            "Models for This API": [.zh: "此 API 的模型", .en: "Models for This API"],
            "Chat Preferences": [.zh: "对话偏好", .en: "Chat Preferences"],
            "Delete API": [.zh: "删除 API", .en: "Delete API"],
            "New API": [.zh: "新 API", .en: "New API"],
            "Context Budget": [.zh: "上下文预算", .en: "Context Budget"],
            "Save the configuration, then select a model in chat.": [.zh: "填写后保存，再到聊天中选择模型。", .en: "Save the configuration, then select a model in chat."],
            "Saved. Choose the API and model in the model picker.": [.zh: "已保存；请在模型选择器中选择所需 API 和型号。", .en: "Saved. Choose the API and model in the model picker."],
            "Keychain access failed (code %@).": [.zh: "钥匙串访问失败（错误码 %@）。", .en: "Keychain access failed (code %@)."],
            "Default AI Memory": [.zh: "你是一个理论物理学家。请用物理学家的口吻回答，并尽量使用数学公式。", .en: "You are a theoretical physicist. Respond in that style and use mathematical formulas where appropriate."],
            "请输入 API 名称和有效的 HTTPS Base URL（如 https://api.deepseek.com）；不要附加 /chat/completions。": [.zh: "请输入 API 名称和有效的 HTTPS Base URL（如 https://api.deepseek.com）；不要附加 /chat/completions。", .en: "Enter an API name and a valid HTTPS base URL, such as https://api.deepseek.com, without /chat/completions."],
            "API 名称已存在。请为不同接口/密钥设置可区分的名称，例如 DeepSeek 个人、DeepSeek 工作。": [.zh: "API 名称已存在。请为不同接口/密钥设置可区分的名称，例如 DeepSeek 个人、DeepSeek 工作。", .en: "This API name already exists. Use distinct names for different connections or keys, such as DeepSeek Personal and DeepSeek Work."],
            "模型 ID 不能为空、不能含空白或在同一 API 中重复；上下文预算为 4096–1000000。": [.zh: "模型 ID 不能为空、不能含空白或在同一 API 中重复；上下文预算为 4096–1000000。", .en: "Model IDs must be nonempty, contain no whitespace, and be unique within each API. The context budget must be between 4096 and 1,000,000."],
            "至少添加一个精确的模型 ID。": [.zh: "至少添加一个精确的模型 ID。", .en: "Add at least one exact model ID."],
            "AI Basic Configuration": [.zh: "AI 基础配置", .en: "AI Basic Configuration"],
            "API Protocol": [.zh: "API 协议", .en: "API Protocol"],
            "Base URL Description": [.zh: "配置网络请求的基础地址，支持第三方中转或官方代理。", .en: "Configure the base URL for network requests, supporting third-party proxies."],
            "Model List": [.zh: "模型列表", .en: "Model List"],
            "Comma Separated": [.zh: "以逗号分隔", .en: "Comma separated"],
            "Model List Description": [.zh: "输入你希望在状态栏切换的所有可用模型名称，例如：gpt-4o,deepseek-reasoner", .en: "Enter all available model names you want to switch between in the status bar, e.g., gpt-4o,deepseek-reasoner"],
            "Shortcut Configuration": [.zh: "快捷键配置", .en: "Shortcut Configuration"],
            "Toggle AI Assistant": [.zh: "唤起 AI 助手", .en: "Toggle AI Assistant"],
            "Shortcut Description": [.zh: "设置一个全局快捷键，随时呼出或隐藏 AI 对话面板。", .en: "Set a global shortcut to toggle the AI chat panel at any time."],
            "Global Memory": [.zh: "全局记忆", .en: "Global Memory"],
            "Open Global Memory in Finder": [.zh: "在访达中打开全局记忆配置", .en: "Open Global Memory configuration in Finder"],
            "Global Memory Description": [.zh: "使用与阅读记录相同的本地文件夹存储 GlobalMemory.md，AI 会在每次对话前读取它作为最高物理定律。", .en: "Uses the same local folder as Reading Record to store GlobalMemory.md, which the AI will read before every conversation as its supreme physical law."],
            "Reading Record": [.zh: "阅读记录", .en: "Reading Record"],
            "Enable Reading Record": [.zh: "开启阅读记录", .en: "Enable Reading Record"],
            "Enable Todo": [.zh: "开启待办", .en: "Enable Todo"],
            "Heatmap Granularity": [.zh: "热点图精细度", .en: "Heatmap Granularity"],
            "Heatmap Color": [.zh: "热点图颜色", .en: "Heatmap Color"],
            "Rating Chart Color": [.zh: "评分图颜色", .en: "Rating Chart Color"],
            "Reading Heatmap": [.zh: "阅读热点图", .en: "Reading Heatmap"],
            "Article Date": [.zh: "文章日期", .en: "Article Date"],
            "Authors": [.zh: "作者", .en: "Authors"],
            "Author Name": [.zh: "作者姓名", .en: "Author Name"],
            "Author Bio": [.zh: "作者简介", .en: "Author Bio"],
            "Add Author": [.zh: "添加作者", .en: "Add Author"],
            "Article Summary": [.zh: "文章总结", .en: "Article Summary"],
            "Rating": [.zh: "评分", .en: "Rating"],
            "Score (0-100)": [.zh: "分数 (0-100)", .en: "Score (0-100)"],
            "Coming soon...": [.zh: "即将推出...", .en: "Coming soon..."],
            "Save Location": [.zh: "保存位置", .en: "Save Location"],
            "Change...": [.zh: "更改...", .en: "Change..."],
            "Select": [.zh: "选择", .en: "Select"],
            "Total Time": [.zh: "总时长", .en: "Total Time"],
            "No Reading Record": [.zh: "暂无阅读记录", .en: "No Reading Record"],
            "none": [.zh: "选择", .en: "Select"],
            "highlight": [.zh: "高亮", .en: "Highlight"],
            "underline": [.zh: "下划线", .en: "Underline"],
            "strikeout": [.zh: "删除线", .en: "Strikeout"],
            "ink": [.zh: "手写", .en: "Ink"],
            "Draw": [.zh: "手绘", .en: "Draw"],
            "Insert Blank Page After": [.zh: "在后插入空白页", .en: "Insert Blank Page After"],
            "Insert PDF Before...": [.zh: "在此前插入 PDF...", .en: "Insert PDF Before..."],
            "Insert PDF After...": [.zh: "在此后插入 PDF...", .en: "Insert PDF After..."],
            "Delete Page": [.zh: "删除此页", .en: "Delete Page"],
            "Delete Selected Pages": [.zh: "删除选中页", .en: "Delete Selected Pages"],
            "Open...": [.zh: "打开...", .en: "Open..."],
            "Find...": [.zh: "查找...", .en: "Find..."],
            "Toggle Left Sidebar": [.zh: "切换左侧边栏", .en: "Toggle Left Sidebar"],
            "Toggle Right Sidebar": [.zh: "切换右侧边栏", .en: "Toggle Right Sidebar"],
            "Undo": [.zh: "撤销", .en: "Undo"],
            "Redo": [.zh: "重做", .en: "Redo"],
            "Compare View": [.zh: "对比查看", .en: "Compare View"],
            "Save": [.zh: "保存", .en: "Save"],
            "Print...": [.zh: "打印...", .en: "Print..."],
            "Close Window": [.zh: "关闭窗口", .en: "Close Window"],
            "Page": [.zh: "页", .en: "Page"],
            "Page Number Input": [.zh: "第 %@ 页", .en: "Page %@"],
            "Search Document...": [.zh: "搜索文档...", .en: "Search Document..."],
            "History": [.zh: "历史记录", .en: "History"],
            "Clear": [.zh: "清理", .en: "Clear"],
            "Clear Older Than 7 Days": [.zh: "清理 7 天前记录", .en: "Clear Older Than 7 Days"],
            "Clear Older Than 30 Days": [.zh: "清理 30 天前记录", .en: "Clear Older Than 30 Days"],
            "Clear All (90 Days)": [.zh: "清空所有记录", .en: "Clear All (90 Days)"],
            "Last 7 Days": [.zh: "近 7 天", .en: "Last 7 Days"],
            "Last 30 Days": [.zh: "近 30 天", .en: "Last 30 Days"],
            "Last 90 Days": [.zh: "近 90 天", .en: "Last 90 Days"],
            "No history available.": [.zh: "暂无历史记录。", .en: "No history available."],
            "File Deleted": [.zh: "文件已删除", .en: "File Deleted"],
            "The file '%@' no longer exists or has been deleted.": [.zh: "文件 '%@' 不存在或已被删除。", .en: "The file '%@' no longer exists or has been deleted."],
            "OK": [.zh: "确定", .en: "OK"],
            "No PDF Opened": [.zh: "未打开 PDF", .en: "No PDF Opened"],
            "Open File Description": [.zh: "使用 Cmd+O 打开新文件", .en: "Use Cmd+O to open a file"],
            "iOS Open File Description": [.zh: "点击下方按钮打开文件", .en: "Tap the button below to open"],
            "Open File": [.zh: "打开文件", .en: "Open File"],
            "Language": [.zh: "语言", .en: "Language"],
            "Switch Language": [.zh: "切换语言", .en: "Switch Language"],
            "Annotation Editor": [.zh: "调整标注", .en: "Edit Annotation"],
            "Delete Annotation": [.zh: "删除标注", .en: "Delete Annotation"],
            "Done": [.zh: "完成", .en: "Done"],
            "Core Features": [.zh: "核心功能", .en: "Core"],
            "Color Selection": [.zh: "颜色选择", .en: "Colors"],
            "Annotation Tools": [.zh: "标注工具", .en: "Tools"],
            "Customize Toolbar": [.zh: "定制工具栏", .en: "Customize Toolbar"],
            "Settings": [.zh: "设置", .en: "Settings"],
            "Memory Mode": [.zh: "内存模式", .en: "Memory Mode"],
            "Performance": [.zh: "性能", .en: "High"],
            "Saving": [.zh: "节约", .en: "Low"],
            "Hibernation Timeout": [.zh: "窗口休眠时间", .en: "Hibernation Timeout"],
            "Minutes": [.zh: "分钟", .en: "Minutes"],
            "Never": [.zh: "从不", .en: "Never"],
            "New File Opens In": [.zh: "新文件打开方式", .en: "New File Opens In"],
            "New Window": [.zh: "新窗口", .en: "New Window"],
            "New Tab": [.zh: "新标签页", .en: "New Tab"],
            "Window Hibernating": [.zh: "窗口已休眠以节省内存", .en: "Window Hibernating"],
            "Click anywhere to wake up and restore memory": [.zh: "点击任意位置唤醒并恢复文件", .en: "Click anywhere to wake up and restore memory"],
            "Show Toolbar Groups": [.zh: "显示工具栏组", .en: "Show Toolbar Groups"],
            "Blue": [.zh: "蓝色", .en: "Blue"],
            "Red": [.zh: "红色", .en: "Red"],
            "Yellow": [.zh: "黄色", .en: "Yellow"],
            "Green": [.zh: "绿色", .en: "Green"],
            "Purple": [.zh: "紫色", .en: "Purple"],
            "Color": [.zh: "颜色", .en: "Color"],
            "Enter Slideshow": [.zh: "进入演示", .en: "Enter Slideshow"],
            "Exit Slideshow": [.zh: "退出演示", .en: "Exit Slideshow"],
            "Finder": [.zh: "访达", .en: "Finder"],
            "Right Column": [.zh: "右栏", .en: "Right Sidebar"],
            "Left Column": [.zh: "左栏", .en: "Left Sidebar"],
            "Import": [.zh: "导入", .en: "Import"],
            "Activate Tab": [.zh: "激活标签", .en: "Activate Tab"],
            "Close": [.zh: "关闭", .en: "Close"],
            "Close Others": [.zh: "关闭其他", .en: "Close Others"],
            "External Browser": [.zh: "外部浏览器", .en: "External Browser"],
            "Default Browser": [.zh: "默认浏览器", .en: "Default Browser"],
            "Other Application...": [.zh: "其他应用...", .en: "Other Application..."],
            "Annotation": [.zh: "标注", .en: "Annotation"],
            "Revert to Selection After": [.zh: "自动恢复选择工具", .en: "Revert to Selection After"],
            "Seconds": [.zh: "秒", .en: "Seconds"],
            "Highlight Default Color": [.zh: "高亮默认颜色", .en: "Highlight Default Color"],
            "Underline Default Color": [.zh: "下划线默认颜色", .en: "Underline Default Color"],
            "Strikeout Default Color": [.zh: "删除线默认颜色", .en: "Strikeout Default Color"],
            "Ink Default Color": [.zh: "手绘默认颜色", .en: "Ink Default Color"],
            "Line Weight": [.zh: "线条粗细", .en: "Line Weight"],
            "Weight": [.zh: "粗细", .en: "Weight"],
            "General": [.zh: "通用", .en: "General"],
            "Shortcuts": [.zh: "快捷键", .en: "Shortcuts"],
            "File Operations": [.zh: "文件操作", .en: "File Operations"],
            "Navigation": [.zh: "导航", .en: "Navigation"],
            "Other Color...": [.zh: "其他颜色...", .en: "Other Color..."],
            "Global Authors Library": [.zh: "全局作者库", .en: "Global Authors Library"],
            "Works": [.zh: "个作品", .en: "Works"],
            "Select an author": [.zh: "请选择一个作者", .en: "Select an author"],
            "Name": [.zh: "姓名", .en: "Name"],
            "First Name": [.zh: "名", .en: "First Name"],
            "Last Name": [.zh: "姓", .en: "Last Name"],
            "Sort by Pinyin": [.zh: "按姓氏拼音排序", .en: "Sort by Last Name"],
            "Sort by Works Count": [.zh: "按作品数量排序", .en: "Sort by Works Count"],
            "Sort Method": [.zh: "排序方式", .en: "Sort Method"],
            "Open in Browser": [.zh: "在浏览器中打开", .en: "Open in Browser"],
            "Delete": [.zh: "删除", .en: "Delete"],
            "No authors recorded yet.": [.zh: "暂无记录的作者", .en: "No authors recorded yet."],
            "Restore Defaults": [.zh: "恢复默认设置", .en: "Restore Defaults"],
            "Signature": [.zh: "签名", .en: "Signature"],
            "Rotate Left": [.zh: "向左旋转", .en: "Rotate Left"],
            "Browser": [.zh: "浏览器打开", .en: "Browser"],
            "Comparison": [.zh: "对比查看", .en: "Comparison"],
            "Icon Only": [.zh: "仅图标", .en: "Icon Only"],
            "Icon and Text": [.zh: "图标和文本", .en: "Icon and Text"],
            "Customize Toolbar...": [.zh: "自定义工具栏...", .en: "Customize Toolbar..."],
            "Bio": [.zh: "简介", .en: "Bio"],
            "General Options": [.zh: "常规选项", .en: "General Options"],
            "Burn-in Annotations...": [.zh: "烧录", .en: "Burn-in Annotations..."],
            "Reveal in Finder": [.zh: "在访达中显示", .en: "Reveal in Finder"],
            "Slideshow": [.zh: "幻灯片", .en: "Slideshow"],
            "New Blank File...": [.zh: "新建空文件...", .en: "New Blank File..."],
            "New Blank Document": [.zh: "新建空文件", .en: "New Blank Document"],
            "Document Properties": [.zh: "文档属性", .en: "Document Properties"],
            "File Type:": [.zh: "文件类型:", .en: "File Type:"],
            "Paper Size:": [.zh: "纸张尺寸:", .en: "Paper Size:"],
            "Width": [.zh: "宽度", .en: "Width"],
            "Height": [.zh: "高度", .en: "Height"],
            "Save Options": [.zh: "保存选项", .en: "Save Options"],
            "File Name:": [.zh: "文件名称:", .en: "File Name:"],
            "Untitled": [.zh: "未命名", .en: "Untitled"],
            "Save To:": [.zh: "保存至:", .en: "Save To:"],
            "Browse...": [.zh: "浏览...", .en: "Browse..."],
            "Cancel": [.zh: "取消", .en: "Cancel"],
            "Create": [.zh: "创建", .en: "Create"],
            "Default Background": [.zh: "默认背景", .en: "Default Background"],
            "Eye-care Green": [.zh: "护眼绿", .en: "Eye-care Green"],
            "Soft Yellow": [.zh: "柔和黄", .en: "Soft Yellow"],
            "Dark Mode": [.zh: "暗黑模式", .en: "Dark Mode"],
            "Background Color": [.zh: "背景颜色", .en: "Background Color"],
            "Untitled Document": [.zh: "未命名文档", .en: "Untitled Document"],
            "Untitled Group": [.zh: "未命名分组", .en: "Untitled Group"],
            "No open documents": [.zh: "暂无打开的文档", .en: "No open documents"],
            "New Group": [.zh: "新建分组", .en: "New Group"],
            "Tab Groups": [.zh: "标签页分组", .en: "Tab Groups"],
            "Group": [.zh: "分组", .en: "Group"],
            "Check for Updates...": [.zh: "检查更新...", .en: "Check for Updates..."],
            "Automatically check for updates": [.zh: "自动检查更新", .en: "Automatically check for updates"],
            "Default Application": [.zh: "默认应用", .en: "Default Application"],
            "Set as Default Viewer": [.zh: "设为默认查看器", .en: "Set as Default Viewer"],
            "Set as Default PDF Viewer": [.zh: "设为默认 PDF 阅读器", .en: "Set as Default PDF Viewer"],
            "Set as Default Image Viewer": [.zh: "设为默认图片查看器", .en: "Set as Default Image Viewer"],
            "All Supported Formats": [.zh: "所有支持的格式", .en: "All Supported Formats"],
            "All Supported Images": [.zh: "所有支持的图片", .en: "All Supported Images"],
            "Up to date": [.zh: "当前已是最新版本", .en: "Up to date"],
            "You are using the latest version of SimPleview.": [.zh: "您正在使用最新版本的 SimPleview。", .en: "You are using the latest version of SimPleview."],
            "Update Available": [.zh: "发现新版本", .en: "Update Available"],
            "A new version is available!": [.zh: "发现新版本，是否前往下载？", .en: "A new version is available! Do you want to download it?"],
            "Network error while checking for updates.": [.zh: "检查更新时网络连接失败，请稍后重试。", .en: "Network error while checking for updates."],
            "Download": [.zh: "去下载", .en: "Download"],
            "15 Minutes": [.zh: "15 分钟", .en: "15 Minutes"],
            "30 Minutes": [.zh: "30 分钟", .en: "30 Minutes"],
            "60 Minutes": [.zh: "60 分钟", .en: "60 Minutes"]
    ]
    static func s(_ key: String, _ lang: AppLanguage) -> String {
        return dict[key]?[lang] ?? key
    }
    static func format(_ key: String, _ language: AppLanguage, _ arguments: CVarArg...) -> String {
        String(format: s(key, language), locale: language.locale, arguments: arguments)
    }

}
